--
-- PostgreSQL database dump
--

-- Dumped from database version 14.12
-- Dumped by pg_dump version 14.12

-- Started on 2025-02-17 12:42:37

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: postgres
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO postgres;

--
-- TOC entry 3327 (class 0 OID 0)
-- Dependencies: 3
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: postgres
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 211 (class 1259 OID 25744)
-- Name: company; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.company (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.company OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 25743)
-- Name: company_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.company ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.company_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 213 (class 1259 OID 25797)
-- Name: room; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.room (
    id bigint NOT NULL,
    address character varying(255) NOT NULL,
    building_name character varying(255) NOT NULL,
    deleted boolean NOT NULL,
    image_url character varying(255) NOT NULL,
    middle_term_price numeric(38,2) NOT NULL,
    nearest_station character varying(255),
    room_number character varying(255) NOT NULL,
    room_type character varying(255) NOT NULL,
    short_term_price numeric(38,2) NOT NULL,
    status character varying(255) NOT NULL,
    company_id bigint,
    CONSTRAINT room_room_type_check CHECK (((room_type)::text = ANY ((ARRAY['ONE_ROOM'::character varying, 'ONE_K'::character varying, 'ONE_DK'::character varying, 'ONE_LDK'::character varying, 'TWO_LDK'::character varying, 'THREE_LDK'::character varying])::text[]))),
    CONSTRAINT room_status_check CHECK (((status)::text = ANY ((ARRAY['AVAILABLE'::character varying, 'BOOKING'::character varying])::text[])))
);


ALTER TABLE public.room OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 25796)
-- Name: room_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.room ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.room_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 25736)
-- Name: seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.seq OWNER TO postgres;

--
-- TOC entry 3319 (class 0 OID 25744)
-- Dependencies: 211
-- Data for Name: company; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.company (id, name) FROM stdin;
1	Company A
2	Company B
3	Company C
\.


--
-- TOC entry 3321 (class 0 OID 25797)
-- Dependencies: 213
-- Data for Name: room; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.room (id, address, building_name, deleted, image_url, middle_term_price, nearest_station, room_number, room_type, short_term_price, status, company_id) FROM stdin;
7	Nakamachi 3-chome, Machida City, Tokyo２３－１7	Women's Student House Bricks	f	/images/apartment.jpg	29000.00	12 minutes on foot from MachidaStation	1F	ONE_ROOM	10000.00	AVAILABLE	1
8	Minamiaoyama 7-chome, Minato-ku, Tokyo10-9	BRICK RESIDENCE Minamiaoyama	f	/images/apartment.jpg	185000.00	13 minutes on foot from HiroStation	7F	ONE_DK	15000.00	AVAILABLE	1
10	Ebara 6-chome, Shinagawa-ku, Tokyo18-8	He arrived at Hutte	f	/images/apartment.jpg	72000.00	9 minutes on foot from EbaranakanobuStation	1F	ONE_ROOM	14000.00	AVAILABLE	2
3	Minamiaoyama 7-chome, Minato-ku, Tokyo10-9	BRICK RESIDENCE Minamiaoyama	f	/images/apartment.jpg	411000.00	13 minutes on foot from HiroStation	10F	TWO_LDK	20000.00	AVAILABLE	2
4	Minamiaoyama 7-chome, Minato-ku, Tokyo10-9	BRICK RESIDENCE Minamiaoyama	f	/images/apartment.jpg	191000.00	13 minutes on foot from HiroStation	9F	ONE_DK	16000.00	AVAILABLE	2
6	Midori 3-chome, Sumida-ku, Tokyo１５－１2	Ryogoku East	f	/images/apartment.jpg	177000.00	8 minutes on foot from RyogokuStation	7F	ONE_LDK	12200.00	AVAILABLE	3
1	Nakamachi 3-chome, Machida City, Tokyo２３－１７	Women's Student House Bricks	f	/images/apartment.jpg	29000.00	12 minutes on foot from MachidaStation	1F	ONE_ROOM	10500.00	AVAILABLE	1
2	Nakamachi 3-chome, Machida City, Tokyo２３－１７	Women's Student House Bricks	f	/images/apartment.jpg	34000.00	12 minutes on foot from MachidaStation	2F	ONE_ROOM	10700.00	AVAILABLE	1
5	Shimouma 1-chome, Setagaya-ku, Tokyo8－17	Yutenji Studio	f	/images/apartment.jpg	61700.00	7 minutes on foot from YutenjiStation	1F	ONE_K	6600.00	AVAILABLE	3
11	Chuo 5-chome, Ota Ward, Tokyo21-1	haiku	f	/images/apartment.jpg	132000.00	13 minutes on foot from NishimagomeStation	1F	ONE_LDK	5000.00	AVAILABLE	2
13	Hachioji, Tokyo Yokamachi	pureshisuhachioujiregurio	f	/images/apartment.jpg	235000.00	10 minutes on foot from HachiojiStation	12F	THREE_LDK	15000.00	AVAILABLE	3
12	Soshigaya 1-chome, Setagaya-ku, Tokyo3-12	Soshigaya Branch	f	/images/apartment.jpg	125000.00	4 minutes on foot from SoshigayaokuraStation	1F	ONE_LDK	3000.00	AVAILABLE	2
14	Akatsutsumi 2-chome, Setagaya-ku, Tokyo9－16	long island garden	f	/images/apartment.jpg	285000.00	5 minutes on foot from GotokujiStation	1F	THREE_LDK	5000.00	AVAILABLE	3
15	Tokyo Ota Ward Higashiyukiya 4-chome21－11	rejidensuefuefuemuyukigaya	f	/images/apartment.jpg	240000.00	14 minutes on foot from SenzokuikeStation	5F	THREE_LDK	15000.00	AVAILABLE	3
16	4-chome Higashimachi, Koganei City, Tokyo13-6	N Stage Higashi Koganei	f	/images/apartment.jpg	245000.00	5 minutes on foot from ShinkoganeiStation	3F	THREE_LDK	25000.00	AVAILABLE	3
9	2-chome Minamiotsuka, Toshima-ku, Tokyo2-6	Flat Share SHIN-OTSUKA Campus	f	/images/apartment.jpg	70000.00	5 minutes on foot from ShinotsukaStation	1F	ONE_ROOM	14000.00	BOOKING	1
\.


--
-- TOC entry 3328 (class 0 OID 0)
-- Dependencies: 210
-- Name: company_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.company_id_seq', 3, true);


--
-- TOC entry 3329 (class 0 OID 0)
-- Dependencies: 212
-- Name: room_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.room_id_seq', 16, true);


--
-- TOC entry 3330 (class 0 OID 0)
-- Dependencies: 209
-- Name: seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.seq', 3, true);


--
-- TOC entry 3173 (class 2606 OID 25748)
-- Name: company company_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.company
    ADD CONSTRAINT company_pkey PRIMARY KEY (id);


--
-- TOC entry 3176 (class 2606 OID 25805)
-- Name: room room_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.room
    ADD CONSTRAINT room_pkey PRIMARY KEY (id);


--
-- TOC entry 3174 (class 1259 OID 25806)
-- Name: idx_building_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_building_name ON public.room USING btree (building_name);


--
-- TOC entry 3177 (class 2606 OID 25807)
-- Name: room fk5ohcikk1iwoscgj325a1lbvqh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.room
    ADD CONSTRAINT fk5ohcikk1iwoscgj325a1lbvqh FOREIGN KEY (company_id) REFERENCES public.company(id);


-- Completed on 2025-02-17 12:42:37

--
-- PostgreSQL database dump complete
--

